-- chunkname: @/var/folders/r9/xbxmw8n51957gv9ggzrytvf80000gp/T/com.ironhidegames.frontiers.windows.steam.ep3S4swo/all/constants.lua

NULL = "__NULL__"
FPS = 30
ASPECT = 0.7
REF_W = 1024
REF_H = 768
REF_OX = math.floor((REF_H * 16 / 9 - REF_W) / 2)

if KR_TARGET == "phone" then
	GUI_REF_W = 480
	GUI_REF_H = 320
else
	GUI_REF_W = 1024
	GUI_REF_H = 768
end

WIDE_SCREEN_ASPECT = 1.775
ULTRAWIDE_SCREEN_ASPECT = 2.053125
MIN_SCREEN_ASPECT = KR_TARGET == "phone" and 1.5 or 1.3333333333333333
MAX_SCREEN_ASPECT = KR_TARGET == "phone" and 2.165 or 1.7777777777777777
SAFE_FRAME_STEPS = {
	{
		ULTRAWIDE_SCREEN_ASPECT,
		KR_PLATFORM == "ios" and {
			b = 10,
			l = 30,
			r = 30,
			t = 6
		} or {
			b = 10,
			l = 14,
			r = 14,
			t = 6
		}
	},
	{
		WIDE_SCREEN_ASPECT,
		{
			b = 0,
			l = 0,
			r = 0,
			t = 0
		}
	},
	{
		0,
		{
			b = 0,
			l = 0,
			r = 0,
			t = 0
		}
	}
}
HUD_SCALE_STEPS = {
	{
		ULTRAWIDE_SCREEN_ASPECT,
		1
	},
	{
		WIDE_SCREEN_ASPECT,
		1
	},
	{
		0,
		0.85
	}
}
TEXTURE_SIZE_ALIAS = {
	iphone = 480,
	ipadhd = 1536,
	ipad = 768,
	iphonehd = 960,
	fullhd = 1080
}
TEXTURE_SIZE_FACTOR = {
	iphonehd = {
		game = 0.95,
		game_editor = 0.95
	}
}
HOVER_PULSE_PERIOD = 0.66
HOVER_PULSE_ALPHA_MAX = 1
HOVER_PULSE_ALPHA_MIN = 0.6
HOVER_PULSE_ALPHA_MAX_INGAME = 229.5
HOVER_PULSE_ALPHA_MIN_INGAME = 153
Z_BACKGROUND = 1000
Z_BACKGROUND_BETWEEN = 1100
Z_BACKGROUND_COVERS = 1200
Z_TOWER_BASES = 1300
Z_DECALS = 1400
Z_GUI_DECALS = 2000
Z_OBJECTS = 3000
Z_OBJECTS_COVERS = 3100
Z_FLYING_HEROES = 3150
Z_BULLET_PARTICLES = 3200
Z_EFFECTS = 3300
Z_BULLETS = 3400
Z_OBJECTS_SKY = 3500
Z_SCREEN_FIXED = 3900
Z_GUI = 4000
GUI_MODE_IDLE = "IDLE"
GUI_MODE_RALLY_TOWER = "RALLY_TOWER"
GUI_MODE_RALLY_HERO = "RALLY_HERO"
GUI_MODE_POWER_1 = "POWER_1"
GUI_MODE_POWER_2 = "POWER_2"
GUI_MODE_POWER_3 = "POWER_3"
GUI_MODE_BAG = "BAG"
GUI_MODE_BAG_ITEM = "BAG_ITEM"
GUI_MODE_TOWER_MENU = "TOWER_MENU"
GUI_MODE_PAUSE = "PAUSE"
GUI_MODE_NOTIFICATION = "NOTIFICATION"
GUI_MODE_WAVE_FLAG = "WAVE_FLAG"
GUI_MODE_SELECT_POINT = "SELECT_POINT"
GUI_MODE_POINTER = "POINTER"
GUI_MODE_DISABLED = "DISABLED"
GUI_MODE_FINISHED = "FINISHED"
STATS_TYPE_ENEMY = 1
STATS_TYPE_SOLDIER = 2
STATS_TYPE_TOWER = 3
STATS_TYPE_TOWER_BARRACK = 4
STATS_TYPE_TOWER_MAGE = 5
STATS_TYPE_TOWER_NO_RANGE = 6
STATS_TYPE_TEXT = 9
DAMAGE_TRUE = 1
DAMAGE_PHYSICAL = 2
DAMAGE_MAGICAL = 4
DAMAGE_EXPLOSION = 8
DAMAGE_ELECTRICAL = 16
DAMAGE_POISON = 32
DAMAGE_ARMOR = 256
DAMAGE_MAGICAL_ARMOR = 512
DAMAGE_INSTAKILL = 1024
DAMAGE_DISINTEGRATE = 2048
DAMAGE_EAT = 4096
DAMAGE_HOST = 8192
DAMAGE_DISINTEGRATE_BOSS = 16384
DAMAGE_MODIFIER = 32768
DAMAGE_NO_KILL = 8388608
DAMAGE_NO_SPAWNS = 16777216
DAMAGE_NO_DODGE = 33554432
DAMAGE_NO_LIFESTEAL = 67108864
DAMAGE_NO_SHIELD_HIT = 134217728
DAMAGE_ONE_SHIELD_HIT = 268435456
DAMAGE_IGNORE_SHIELD = 536870912
DAMAGE_FX_NOT_EXPLODE = 1073741824
DAMAGE_FX_EXPLODE = 2147483648
DAMAGE_BASE_TYPES = 255
DAMAGE_ALL_TYPES = 16777215
DAMAGE_ALL_FLAGS = 4278190080
DAMAGE_ALL = 4294967295
DAMAGE_NONE = 0
DR_NONE = 0
DR_DAMAGE = 1
DR_KILL = 2
DR_ARMOR = 4
DR_MAGICAL_ARMOR = 8
TERRAIN_STYLE_GRASS = 1
TERRAIN_STYLE_SNOW = 2
TERRAIN_STYLE_WASTELAND = 3
TERRAIN_STYLE_DESERT = 4
TERRAIN_STYLE_JUNGLE = 5
TERRAIN_STYLE_UNDERGROUND = 6
TERRAIN_STYLE_BEACH = 7
TERRAIN_STYLE_HALLOWEEN = 8
TERRAIN_STYLE_ELVEN_WOODS = 1
TERRAIN_STYLE_FAERIE_GROVE = 2
TERRAIN_STYLE_ANCIENT_METROPOLIS = 3
TERRAIN_STYLE_HULKING_RAGE = 4
TERRAIN_STYLE_BITTERING_RANCOR = 5
TERRAIN_STYLE_FORGOTTEN_TREASURES = 6
TERRAIN_STYLE_BLACKBURN = 8
TERRAIN_STYLES = {
	grass = TERRAIN_STYLE_GRASS,
	snow = TERRAIN_STYLE_SNOW,
	wasteland = TERRAIN_STYLE_WASTELAND,
	desert = TERRAIN_STYLE_DESERT,
	jungle = TERRAIN_STYLE_JUNGLE,
	underground = TERRAIN_STYLE_UNDERGROUND,
	beach = TERRAIN_STYLE_BEACH,
	halloween = TERRAIN_STYLE_HALLOWEEN,
	elvenwoods = TERRAIN_STYLE_ELVEN_WOODS,
	faeriegrove = TERRAIN_STYLE_FAERIE_GROVE,
	metropolis = TERRAIN_STYLE_ANCIENT_METROPOLIS,
	hulkingrage = TERRAIN_STYLE_HULKING_RAGE,
	blackburn = TERRAIN_STYLE_BLACKBURN,
	bitteringrancor = TERRAIN_STYLE_BITTERING_RANCOR,
	forgottentreasures = TERRAIN_STYLE_FORGOTTEN_TREASURES
}
TERRAIN_NONE = 0
TERRAIN_LAND = 1
TERRAIN_WATER = 2
TERRAIN_CLIFF = 4
TERRAIN_NOWALK = 256
TERRAIN_SHALLOW = 512
TERRAIN_FAERIE = 1024
TERRAIN_ICE = 2048
TERRAIN_PROPS_COUNT = 4
TERRAIN_TYPES_MASK = 255
TERRAIN_PROPS_MASK = 65280
TERRAIN_ALL_MASK = 65535
F_BLOCK = 1
F_RANGED = 2
F_MOD = 4
F_AREA = 8
F_HERO = 16
F_BOSS = 32
F_MINIBOSS = 64
F_FLYING = 128
F_CLIFF = 256
F_WATER = 512
F_FRIEND = 1024
F_ENEMY = 2048
F_CUSTOM = 4096
F_LETHAL = 8192
F_LAVA = 16384
F_BURN = 16384
F_CANNIBALIZE = 32768
F_BLOOD = 65536
F_DRILL = 131072
F_DRIDER_POISON = 131072
F_EAT = 262144
F_INSTAKILL = 524288
F_POISON = 1048576
F_POLYMORPH = 2097152
F_STUN = 4194304
F_TELEPORT = 8388608
F_THORN = 16777216
F_TWISTER = 16777216
F_RAGGIFY = 16777216
F_SKELETON = 33554432
F_NET = 67108864
F_DISINTEGRATED = 134217728
F_FREEZE = 268435456
F_ZOMBIE = 536870912
F_SERVANT = 536870912
F_LYCAN = 1073741824
F_DARK_ELF = 1073741824
F_SPELLCASTER = 2147483648
F_NONE = 0
F_ALL = 4294967295
NF_NONE = 0
NF_ALL = 4294967295
NF_RALLY = 1
NF_RANGE = 2
NF_POWER_1 = 128
NF_POWER_2 = 256
NF_POWER_3 = 512
NF_TWISTER = 65536
NF_NO_EXIT = 131072
UNIT_SIZE_NONE = 0
UNIT_SIZE_SMALL = 1
UNIT_SIZE_MEDIUM = 2
UNIT_SIZE_LARGE = 3
TOWER_SIZE_NONE = 0
TOWER_SIZE_SMALL = 1
TOWER_SIZE_LARGE = 3
HEALTH_BAR_SIZE_SMALL = "small"
HEALTH_BAR_SIZE_MEDIUM = "med"
HEALTH_BAR_SIZE_MEDIUM_MEDIUM = "med_med"
HEALTH_BAR_SIZE_MEDIUM_LARGE = "med_big"
HEALTH_BAR_SIZE_LARGE = "big"
HEALTH_BAR_SIZES = {
	fullhd = {
		[HEALTH_BAR_SIZE_SMALL] = {
			x = 22,
			y = 3
		},
		[HEALTH_BAR_SIZE_MEDIUM] = {
			x = 34,
			y = 3
		},
		[HEALTH_BAR_SIZE_MEDIUM_MEDIUM] = {
			x = 42,
			y = 4
		},
		[HEALTH_BAR_SIZE_MEDIUM_LARGE] = {
			x = 62,
			y = 4
		},
		[HEALTH_BAR_SIZE_LARGE] = {
			x = 110,
			y = 4
		}
	},
	default = {
		[HEALTH_BAR_SIZE_SMALL] = {
			x = 16,
			y = 2
		},
		[HEALTH_BAR_SIZE_MEDIUM] = {
			x = 24,
			y = 2
		},
		[HEALTH_BAR_SIZE_MEDIUM_MEDIUM] = {
			x = 30,
			y = 3
		},
		[HEALTH_BAR_SIZE_MEDIUM_LARGE] = {
			x = 44,
			y = 3
		},
		[HEALTH_BAR_SIZE_LARGE] = {
			x = 78,
			y = 3
		}
	}
}
HEALTH_BAR_COLORS = {
	black = {
		0,
		0,
		0,
		255
	},
	bg = {
		126,
		0,
		12,
		255
	},
	fg = {
		68,
		174,
		50,
		255
	}
}
HEALTH_BAR_CORNER_DOT_QUAD = {
	0,
	0,
	1,
	1,
	1024,
	1024
}
BLOOD_NONE = nil
BLOOD_RED = "red"
BLOOD_GREEN = "green"
BLOOD_GRAY = "gray"
BLOOD_VIOLET = "violet"
BLOOD_ORANGE = "orange"
GAME_MODE_CAMPAIGN = 1
GAME_MODE_HEROIC = 2
GAME_MODE_IRON = 3
GAME_MODE_ENDLESS = 4
DIFFICULTY_EASY = 1
DIFFICULTY_NORMAL = 2
DIFFICULTY_HARD = 3
DIFFICULTY_IMPOSSIBLE = 4
COUNT_GROUP_CONCURRENT = 1
COUNT_GROUP_CUMULATIVE = 2
N_ENEMY = 1
N_POWER = 2
N_TIP = 3
N_TOWER = 4
N_TOWER_2 = 5
N_TOWER_4 = 6
N_TUTORIAL = 7
P_LIFETIME = 1
P_LEVEL = 2
P_WAVE = 3
P_SESSION = 4
P_POWER_1 = 5
A_NO_TARGET = 1
A_IN_COOLDOWN = 2
A_DONE = 3
KEYPRESS_ESCAPE = "escape"
KEYPRESS_SPACE = "space"
KEYPRESS_RETURN = "return"
KEYPRESS_1 = "1"
KEYPRESS_2 = "2"
KEYPRESS_3 = "3"
KEYPRESS_4 = "4"
KEYPRESS_5 = "5"
KEYPRESS_6 = "6"
KEYPRESS_Q = "q"
KEYPRESS_W = "w"
KEYPRESS_F1 = "f1"
KEYPRESS_F2 = "f2"
KEYPRESS_F3 = "f3"
KEYPRESS_F4 = "f4"
KEYPRESS_F5 = "f5"
KEYPRESS_F6 = "f6"
PT_NUMBER = "number"
PT_STRING = "string"
PT_COORDS = "coords"
PT_COLOR = "color"
DEVICE_PROFILE_LOW = 1
DEVICE_PROFILE_MEDIUM = 2
DEVICE_PROFILE_HIGH = 3
ALERT_NODES_TO_DEFEND = 35
MOD_TYPE_BLEED = "bleed"
MOD_TYPE_FAST = "fast"
MOD_TYPE_FREEZE = "freeze"
MOD_TYPE_POISON = "poison"
MOD_TYPE_POLYMORPH = "polymorph"
MOD_TYPE_RAGE = "rage"
MOD_TYPE_SLOW = "slow"
MOD_TYPE_STUN = "stun"
MOD_TYPE_TELEPORT = "teleport"
MOD_TYPE_TIMELAPSE = "timelapse"
AD_TYPE_REWARDED = "rewarded"
AD_TYPE_INTERSTITIAL = "interstitial"
SGN_PS_STATUS_CHANGED = "platform-service-status-changed"
SGN_PS_SYNC_SLOTS_FINISHED = "platform-service-sync-slots-finished"
SGN_PS_PUSH_SLOT_FINISHED = "platform-service-push-slot-finished"
SGN_PS_DELETE_SLOT_FINISHED = "platform-service-delete-slot-finished"
SGN_PS_SYNC_PRODUCTS_FINISHED = "platform-service-sync-products-finished"
SGN_PS_SYNC_PURCHASES_FINISHED = "platform-service-sync-purchases-finished"
SGN_PS_SYNC_PURCHASE_HISTORY_FINISHED = "platform-service-sync-purchase-history-finished"
SGN_PS_PURCHASE_PRODUCT_FINISHED = "platform-service-purchase-product-finished"
SGN_PS_PREMIUM_UNLOCKED = "platform-service-premium-unlocked"
SGN_PS_AD_SHOW_VIDEO_STARTED = "platform-service-ad-show-video-started"
SGN_PS_AD_SHOW_VIDEO_FINISHED = "platform-service-ad-show-video-finished"
SGN_PS_REMOTE_CONFIG_SYNC_FINISHED = "platform-service-remote-config-sync-finished"
SGN_PS_SYNC_ACHIEVEMENTS_FINISHED = "platform-service-achievements-sync-finished"
SGN_PS_CHECK_DRM_FINISHED = "platform-service-check-drm-finished"
SGN_PS_NEWS_CACHED = "platfor-service-news-cached"
SGN_PS_NEWS_IMAGE_CACHED = "platfor-service-news-image-cached"
SGN_PS_HTTP_GET_FINISHED = "platform-service-http-get-finished"
SGN_FS_COMMIT_STARTED = "filesystem-commit-started"
SGN_FS_COMMIT_ENDED = "filesystem-commit-ended"
SGN_REMOTE_CONFIG_UPDATED = "remote-config-updated"
SGN_MARKETING_OFFER_SHOWN = "marketing-offer-shown"
SGN_MARKETING_OFFER_ICON_TOUCHED = "marketing-offer-icon-touched"
SGN_DIRECTOR_ITEM_SHOWN = "director-item-shown"
SGN_GAME_GUI_PAUSE_SHOW = "game-gui-pause-show"
SGN_GAME_GUI_PAUSE_HIDE = "game-gui-pause-hide"
SGN_SHOP_GEMS_CHANGED = "shop-gems-changed"
SGN_SHOP_SHOW_IAP_PROGRESS = "shop-show-iap-progress"
SGN_SHOP_SHOW_MESSAGE = "shop-show-message"
SGN_SHOW_GEMS_STORE = "show-gems-store"
SGN_SHOP_SHOWN = "shop-shown"
SGN_SHOP_HIDDEN = "shop-hidden"
SGN_FULLADS_WORKFLOW_ICON_TOUCHED = "fullads-workflow-icon-touched"
SGN_FULLADS_SHOW_MESSAGE = "fullads-show-message"
SGN_FULLADS_REWARDS_SHOWN = "fullads-rewards-shown"
SGN_FULLADS_REWARDS_HIDDEN = "fullads-rewards-hidden"
